import { Heading, Box, Text } from "@chakra-ui/react";
import Head from "next/head";

import events from "@/src/data/live-coding/events-english.json"

export default function LiveCoding() {
  return (
    <>
      <Head>
        <title>PPBL 2023</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box w="50%" mx="auto">
        <Heading py="10" size="4xl">Live Coding</Heading>

        <Heading>Gimbalabs - English</Heading>
        {events.events.map((event: any, i) => (
          <Box key={i} m="3" p="3" bg="theme.green" color="theme.dark">
            <Text fontSize="lg" fontWeight="bold">{event.title}</Text>
            <Text>{event.date}</Text>
            <Text>{event.description}</Text>
          </Box>
        ))}
        <Heading>Gimbalabs Indonesia</Heading>

        <Heading>Gimbalabs Vietnam</Heading>
      </Box>
    </>
  );
}
